# OPTIMAL_PLAN = 'plans/plan_1_optimal.txt'
DOMAIN = 'domains/original/blocksworld/domain.pddl'
PROBLEM = 'domains/original/blocksworld/instances/instance-1.pddl'
PLAN = 'plans/plan_1.txt'
MODEL = 'openai/gpt-oss-20b'