(define (problem logistics_route_dispatch_north_prefix_15_p2)
  (:domain driver_shift_compliant_route_planning)
  (:objects origin_availability_north - origin_candidate_availability destination_availability_north - destination_candidate_availability shift_candidate_north_primary - schedule_candidate shift_candidate_north_relay - schedule_candidate vehicle_unit_north_origin - vehicle_unit vehicle_unit_north_destination - vehicle_unit vehicle_unit_north_linehaul - vehicle_unit route_task_profile_north - route_task_profile driver_operator_north - operator_resource cargo_payload_north - cargo_payload origin_node_north - origin_node destination_node_north - destination_node transport_leg_north - transport_leg loading_container_north_primary - loading_container loading_container_north_relay - loading_container equipment_resource_north_lift - equipment_resource equipment_resource_north_dock - equipment_resource service_window_north_early - service_window service_window_north_late - service_window dispatch_slot_north - dispatch_slot skill_certificate_north - skill_certificate operational_constraint_north_primary - operational_constraint operational_constraint_north_relay - operational_constraint compliance_certificate_north - compliance_certificate)
  (:init
(vehicle_available vehicle_unit_north_origin)
    (vehicle_available vehicle_unit_north_destination)
    (vehicle_available vehicle_unit_north_linehaul)
    (route_task_profile_available route_task_profile_north)
    (operator_available driver_operator_north)
    (cargo_available cargo_payload_north)
    (origin_availability_node_linked origin_availability_north origin_node_north)
    (destination_availability_node_linked destination_availability_north destination_node_north)
    (transport_leg_available transport_leg_north)
    (loading_container_available loading_container_north_primary)
    (loading_container_available loading_container_north_relay)
    (candidate_origin_availability_linked shift_candidate_north_primary origin_availability_north)
    (candidate_origin_availability_linked shift_candidate_north_relay origin_availability_north)
    (candidate_destination_availability_linked shift_candidate_north_primary destination_availability_north)
    (candidate_destination_availability_linked shift_candidate_north_relay destination_availability_north)
    (candidate_transport_leg_linked shift_candidate_north_primary transport_leg_north)
    (candidate_transport_leg_linked shift_candidate_north_relay transport_leg_north)
    (candidate_loading_container_linked shift_candidate_north_primary loading_container_north_primary)
    (candidate_loading_container_linked shift_candidate_north_relay loading_container_north_relay)
    (equipment_available equipment_resource_north_lift)
    (equipment_available equipment_resource_north_dock)
    (service_window_available service_window_north_early)
    (service_window_available service_window_north_late)
    (dispatch_slot_available dispatch_slot_north)
    (skill_certificate_available skill_certificate_north)
    (operational_constraint_available operational_constraint_north_primary)
    (candidate_operational_constraint_linked shift_candidate_north_primary operational_constraint_north_primary)
    (candidate_operational_constraint_linked shift_candidate_north_relay operational_constraint_north_relay)
    (compliance_certificate_available compliance_certificate_north)
  )
  (:goal
    (and
      (dispatch_ready shift_candidate_north_primary)
      (operator_available driver_operator_north)
      (candidate_created destination_availability_north)
      (candidate_created shift_candidate_north_relay)
      (vehicle_allocated origin_availability_north)
      (candidate_vehicle_linked origin_availability_north vehicle_unit_north_origin)
    )
  )
)
