(define (problem logistics_route_dispatch_port_slice_30_p4)
  (:domain driver_shift_compliant_route_planning)
  (:objects origin_availability_port - origin_candidate_availability destination_availability_port - destination_candidate_availability shift_candidate_port_primary - schedule_candidate shift_candidate_port_relay - schedule_candidate vehicle_unit_port_origin - vehicle_unit vehicle_unit_port_destination - vehicle_unit vehicle_unit_port_linehaul - vehicle_unit route_task_profile_port - route_task_profile driver_operator_port - operator_resource cargo_payload_port - cargo_payload origin_node_port - origin_node destination_node_port - destination_node transport_leg_port - transport_leg loading_container_port_primary - loading_container loading_container_port_relay - loading_container equipment_resource_port_lift - equipment_resource equipment_resource_port_dock - equipment_resource service_window_port_early - service_window service_window_port_late - service_window dispatch_slot_port - dispatch_slot skill_certificate_port - skill_certificate operational_constraint_port_primary - operational_constraint operational_constraint_port_relay - operational_constraint compliance_certificate_port - compliance_certificate)
  (:init
    (candidate_compliance_certificate_linked shift_candidate_port_primary compliance_certificate_port)
    (candidate_created destination_availability_port)
    (candidate_created origin_availability_port)
    (candidate_created shift_candidate_port_primary)
    (candidate_created shift_candidate_port_relay)
    (candidate_destination_availability_linked shift_candidate_port_primary destination_availability_port)
    (candidate_destination_availability_linked shift_candidate_port_relay destination_availability_port)
    (candidate_dispatch_slot_linked shift_candidate_port_primary dispatch_slot_port)
    (candidate_finalized shift_candidate_port_primary)
    (candidate_loading_container_linked shift_candidate_port_primary loading_container_port_primary)
    (candidate_loading_container_linked shift_candidate_port_relay loading_container_port_relay)
    (candidate_operational_constraint_linked shift_candidate_port_primary operational_constraint_port_primary)
    (candidate_operational_constraint_linked shift_candidate_port_relay operational_constraint_port_relay)
    (candidate_origin_availability_linked shift_candidate_port_primary origin_availability_port)
    (candidate_origin_availability_linked shift_candidate_port_relay origin_availability_port)
    (candidate_prepared destination_availability_port)
    (candidate_prepared shift_candidate_port_primary)
    (candidate_task_profile_linked destination_availability_port route_task_profile_port)
    (candidate_transport_leg_linked shift_candidate_port_primary transport_leg_port)
    (candidate_transport_leg_linked shift_candidate_port_relay transport_leg_port)
    (candidate_vehicle_linked destination_availability_port vehicle_unit_port_destination)
    (candidate_vehicle_linked origin_availability_port vehicle_unit_port_origin)
    (candidate_vehicle_linked shift_candidate_port_primary vehicle_unit_port_linehaul)
    (cargo_available cargo_payload_port)
    (compliance_validation_complete shift_candidate_port_primary)
    (constraint_applied shift_candidate_port_primary)
    (destination_availability_confirmed destination_availability_port)
    (destination_availability_locked destination_availability_port)
    (destination_availability_node_linked destination_availability_port destination_node_port)
    (destination_node_occupied destination_node_port)
    (destination_node_ready destination_node_port)
    (dispatch_allocated shift_candidate_port_primary)
    (dispatch_ready shift_candidate_port_primary)
    (dispatch_slot_available dispatch_slot_port)
    (dispatched shift_candidate_port_primary)
    (equipment_available equipment_resource_port_dock)
    (equipment_available equipment_resource_port_lift)
    (loading_container_available loading_container_port_primary)
    (loading_container_available loading_container_port_relay)
    (operator_alignment_confirmed shift_candidate_port_primary)
    (operator_available driver_operator_port)
    (origin_availability_node_linked origin_availability_port origin_node_port)
    (service_window_available service_window_port_early)
    (service_window_available service_window_port_late)
    (skill_certificate_available skill_certificate_port)
    (transport_leg_available transport_leg_port)
    (vehicle_allocated destination_availability_port)
    (vehicle_allocated origin_availability_port)
    (vehicle_allocated shift_candidate_port_primary)
    (vehicle_available vehicle_unit_port_linehaul)
  )
  (:goal
    (and
      (candidate_clearance_established shift_candidate_port_relay)
      (candidate_compliance_certificate_linked shift_candidate_port_relay compliance_certificate_port)
      (candidate_dispatch_slot_linked destination_availability_port dispatch_slot_port)
      (candidate_dispatch_slot_linked origin_availability_port dispatch_slot_port)
      (candidate_dispatch_slot_linked shift_candidate_port_relay dispatch_slot_port)
      (candidate_finalized shift_candidate_port_relay)
      (candidate_loading_verified shift_candidate_port_relay)
      (candidate_operator_linked shift_candidate_port_relay driver_operator_port)
      (candidate_prepared origin_availability_port)
      (candidate_prepared shift_candidate_port_relay)
      (candidate_skill_certificate_linked shift_candidate_port_relay skill_certificate_port)
      (candidate_staged_for_loading shift_candidate_port_relay)
      (candidate_task_profile_linked shift_candidate_port_relay route_task_profile_port)
      (candidate_vehicle_linked shift_candidate_port_relay vehicle_unit_port_linehaul)
      (dispatch_allocated destination_availability_port)
      (dispatch_allocated origin_availability_port)
      (dispatch_allocated shift_candidate_port_relay)
      (dispatch_ready destination_availability_port)
      (dispatch_ready origin_availability_port)
      (dispatch_ready shift_candidate_port_relay)
      (dispatched destination_availability_port)
      (dispatched origin_availability_port)
      (dispatched shift_candidate_port_relay)
      (loading_container_leg_linked loading_container_port_relay transport_leg_port)
      (loading_container_loaded loading_container_port_relay)
      (origin_availability_confirmed origin_availability_port)
      (origin_availability_locked origin_availability_port)
      (origin_node_occupied origin_node_port)
      (origin_node_ready origin_node_port)
      (transport_leg_assembled transport_leg_port)
      (transport_leg_destination_linked transport_leg_port destination_node_port)
      (transport_leg_loading_authorized transport_leg_port)
      (transport_leg_origin_linked transport_leg_port origin_node_port)
      (vehicle_allocated shift_candidate_port_relay)
      (vehicle_available vehicle_unit_port_destination)
      (vehicle_available vehicle_unit_port_origin)
    )
  )
)
