(define (problem logistics_route_dispatch_cold_slice_22_p3)
  (:domain driver_shift_compliant_route_planning)
  (:objects origin_availability_cold - origin_candidate_availability destination_availability_cold - destination_candidate_availability shift_candidate_cold_primary - schedule_candidate shift_candidate_cold_relay - schedule_candidate vehicle_unit_cold_origin - vehicle_unit vehicle_unit_cold_destination - vehicle_unit vehicle_unit_cold_linehaul - vehicle_unit route_task_profile_cold - route_task_profile driver_operator_cold - operator_resource cargo_payload_cold - cargo_payload origin_node_cold - origin_node destination_node_cold - destination_node transport_leg_cold - transport_leg loading_container_cold_primary - loading_container loading_container_cold_relay - loading_container equipment_resource_cold_lift - equipment_resource equipment_resource_cold_dock - equipment_resource service_window_cold_early - service_window service_window_cold_late - service_window dispatch_slot_cold - dispatch_slot skill_certificate_cold - skill_certificate operational_constraint_cold_primary - operational_constraint operational_constraint_cold_relay - operational_constraint compliance_certificate_cold - compliance_certificate)
  (:init
    (candidate_compliance_certificate_linked shift_candidate_cold_primary compliance_certificate_cold)
    (candidate_created destination_availability_cold)
    (candidate_created origin_availability_cold)
    (candidate_created shift_candidate_cold_primary)
    (candidate_created shift_candidate_cold_relay)
    (candidate_destination_availability_linked shift_candidate_cold_primary destination_availability_cold)
    (candidate_destination_availability_linked shift_candidate_cold_relay destination_availability_cold)
    (candidate_dispatch_slot_linked shift_candidate_cold_primary dispatch_slot_cold)
    (candidate_finalized shift_candidate_cold_primary)
    (candidate_loading_container_linked shift_candidate_cold_primary loading_container_cold_primary)
    (candidate_loading_container_linked shift_candidate_cold_relay loading_container_cold_relay)
    (candidate_operational_constraint_linked shift_candidate_cold_primary operational_constraint_cold_primary)
    (candidate_operational_constraint_linked shift_candidate_cold_relay operational_constraint_cold_relay)
    (candidate_origin_availability_linked shift_candidate_cold_primary origin_availability_cold)
    (candidate_origin_availability_linked shift_candidate_cold_relay origin_availability_cold)
    (candidate_prepared shift_candidate_cold_primary)
    (candidate_transport_leg_linked shift_candidate_cold_primary transport_leg_cold)
    (candidate_transport_leg_linked shift_candidate_cold_relay transport_leg_cold)
    (candidate_vehicle_linked origin_availability_cold vehicle_unit_cold_origin)
    (candidate_vehicle_linked shift_candidate_cold_primary vehicle_unit_cold_linehaul)
    (cargo_available cargo_payload_cold)
    (compliance_validation_complete shift_candidate_cold_primary)
    (constraint_applied shift_candidate_cold_primary)
    (destination_availability_node_linked destination_availability_cold destination_node_cold)
    (dispatch_allocated shift_candidate_cold_primary)
    (dispatch_ready shift_candidate_cold_primary)
    (equipment_available equipment_resource_cold_dock)
    (equipment_available equipment_resource_cold_lift)
    (loading_container_available loading_container_cold_primary)
    (loading_container_available loading_container_cold_relay)
    (operator_alignment_confirmed shift_candidate_cold_primary)
    (operator_available driver_operator_cold)
    (origin_availability_node_linked origin_availability_cold origin_node_cold)
    (route_task_profile_available route_task_profile_cold)
    (service_window_available service_window_cold_early)
    (service_window_available service_window_cold_late)
    (skill_certificate_available skill_certificate_cold)
    (transport_leg_available transport_leg_cold)
    (vehicle_allocated origin_availability_cold)
    (vehicle_allocated shift_candidate_cold_primary)
    (vehicle_available vehicle_unit_cold_destination)
  )
  (:goal
    (and
      (candidate_dispatch_slot_linked destination_availability_cold dispatch_slot_cold)
      (candidate_dispatch_slot_linked origin_availability_cold dispatch_slot_cold)
      (candidate_prepared destination_availability_cold)
      (candidate_prepared origin_availability_cold)
      (candidate_task_profile_linked destination_availability_cold route_task_profile_cold)
      (candidate_vehicle_linked destination_availability_cold vehicle_unit_cold_destination)
      (candidate_vehicle_linked shift_candidate_cold_relay vehicle_unit_cold_linehaul)
      (compliance_certificate_available compliance_certificate_cold)
      (destination_availability_confirmed destination_availability_cold)
      (destination_availability_locked destination_availability_cold)
      (destination_node_occupied destination_node_cold)
      (destination_node_ready destination_node_cold)
      (dispatch_allocated destination_availability_cold)
      (dispatch_allocated origin_availability_cold)
      (dispatch_ready destination_availability_cold)
      (dispatch_ready origin_availability_cold)
      (dispatched origin_availability_cold)
      (dispatched shift_candidate_cold_primary)
      (origin_availability_confirmed origin_availability_cold)
      (origin_availability_locked origin_availability_cold)
      (origin_node_occupied origin_node_cold)
      (origin_node_ready origin_node_cold)
      (transport_leg_assembled transport_leg_cold)
      (transport_leg_destination_linked transport_leg_cold destination_node_cold)
      (transport_leg_loading_authorized transport_leg_cold)
      (transport_leg_origin_linked transport_leg_cold origin_node_cold)
      (vehicle_allocated destination_availability_cold)
      (vehicle_allocated shift_candidate_cold_relay)
      (vehicle_available vehicle_unit_cold_origin)
    )
  )
)
