(define (problem logistics_route_dispatch_port_p18)
  (:domain driver_shift_compliant_route_planning)
  (:objects origin_availability_port - origin_candidate_availability destination_availability_port - destination_candidate_availability shift_candidate_port_primary - schedule_candidate shift_candidate_port_relay - schedule_candidate vehicle_unit_port_origin - vehicle_unit vehicle_unit_port_destination - vehicle_unit vehicle_unit_port_linehaul - vehicle_unit route_task_profile_port - route_task_profile driver_operator_port - operator_resource cargo_payload_port - cargo_payload origin_node_port - origin_node destination_node_port - destination_node transport_leg_port - transport_leg loading_container_port_primary - loading_container loading_container_port_relay - loading_container equipment_resource_port_lift - equipment_resource equipment_resource_port_dock - equipment_resource service_window_port_early - service_window service_window_port_late - service_window dispatch_slot_port - dispatch_slot skill_certificate_port - skill_certificate operational_constraint_port_primary - operational_constraint operational_constraint_port_relay - operational_constraint compliance_certificate_port - compliance_certificate)
  (:init
(vehicle_available vehicle_unit_port_origin)
    (vehicle_available vehicle_unit_port_destination)
    (vehicle_available vehicle_unit_port_linehaul)
    (route_task_profile_available route_task_profile_port)
    (operator_available driver_operator_port)
    (cargo_available cargo_payload_port)
    (origin_availability_node_linked origin_availability_port origin_node_port)
    (destination_availability_node_linked destination_availability_port destination_node_port)
    (transport_leg_available transport_leg_port)
    (loading_container_available loading_container_port_primary)
    (loading_container_available loading_container_port_relay)
    (candidate_origin_availability_linked shift_candidate_port_primary origin_availability_port)
    (candidate_origin_availability_linked shift_candidate_port_relay origin_availability_port)
    (candidate_destination_availability_linked shift_candidate_port_primary destination_availability_port)
    (candidate_destination_availability_linked shift_candidate_port_relay destination_availability_port)
    (candidate_transport_leg_linked shift_candidate_port_primary transport_leg_port)
    (candidate_transport_leg_linked shift_candidate_port_relay transport_leg_port)
    (candidate_loading_container_linked shift_candidate_port_primary loading_container_port_primary)
    (candidate_loading_container_linked shift_candidate_port_relay loading_container_port_relay)
    (equipment_available equipment_resource_port_lift)
    (equipment_available equipment_resource_port_dock)
    (service_window_available service_window_port_early)
    (service_window_available service_window_port_late)
    (dispatch_slot_available dispatch_slot_port)
    (skill_certificate_available skill_certificate_port)
    (operational_constraint_available operational_constraint_port_primary)
    (candidate_operational_constraint_linked shift_candidate_port_primary operational_constraint_port_primary)
    (candidate_operational_constraint_linked shift_candidate_port_relay operational_constraint_port_relay)
    (compliance_certificate_available compliance_certificate_port)
  )
  (:goal
    (and
      (dispatch_ready shift_candidate_port_primary)
      (operator_available driver_operator_port)
      (candidate_created destination_availability_port)
      (candidate_created shift_candidate_port_relay)
      (vehicle_allocated origin_availability_port)
      (candidate_vehicle_linked origin_availability_port vehicle_unit_port_origin)
    )
  )
)
