(define (problem logistics_route_dispatch_alpha_s19_l19_p14)
  (:domain driver_shift_compliant_route_planning)
  (:objects origin_availability_alpha - origin_candidate_availability destination_availability_alpha - destination_candidate_availability shift_candidate_alpha - schedule_candidate shift_candidate_beta - schedule_candidate vehicle_unit_alpha - vehicle_unit vehicle_unit_beta - vehicle_unit vehicle_unit_gamma - vehicle_unit route_task_profile_alpha - route_task_profile driver_operator_alpha - operator_resource cargo_payload_alpha - cargo_payload origin_node_alpha - origin_node destination_node_alpha - destination_node transport_leg_alpha - transport_leg loading_container_alpha - loading_container loading_container_beta - loading_container equipment_resource_alpha - equipment_resource equipment_resource_beta - equipment_resource service_window_alpha - service_window service_window_beta - service_window dispatch_slot_alpha - dispatch_slot skill_certificate_alpha - skill_certificate operational_constraint_alpha - operational_constraint operational_constraint_beta - operational_constraint compliance_certificate_alpha - compliance_certificate)
  (:init
    (candidate_compliance_certificate_linked shift_candidate_alpha compliance_certificate_alpha)
    (candidate_created destination_availability_alpha)
    (candidate_created origin_availability_alpha)
    (candidate_created shift_candidate_alpha)
    (candidate_created shift_candidate_beta)
    (candidate_destination_availability_linked shift_candidate_alpha destination_availability_alpha)
    (candidate_destination_availability_linked shift_candidate_beta destination_availability_alpha)
    (candidate_dispatch_slot_linked shift_candidate_alpha dispatch_slot_alpha)
    (candidate_finalized shift_candidate_alpha)
    (candidate_loading_container_linked shift_candidate_alpha loading_container_alpha)
    (candidate_loading_container_linked shift_candidate_beta loading_container_beta)
    (candidate_operational_constraint_linked shift_candidate_alpha operational_constraint_alpha)
    (candidate_operational_constraint_linked shift_candidate_beta operational_constraint_beta)
    (candidate_origin_availability_linked shift_candidate_alpha origin_availability_alpha)
    (candidate_origin_availability_linked shift_candidate_beta origin_availability_alpha)
    (candidate_prepared shift_candidate_alpha)
    (candidate_transport_leg_linked shift_candidate_alpha transport_leg_alpha)
    (candidate_transport_leg_linked shift_candidate_beta transport_leg_alpha)
    (candidate_vehicle_linked destination_availability_alpha vehicle_unit_beta)
    (candidate_vehicle_linked origin_availability_alpha vehicle_unit_alpha)
    (candidate_vehicle_linked shift_candidate_alpha vehicle_unit_gamma)
    (cargo_available cargo_payload_alpha)
    (compliance_validation_complete shift_candidate_alpha)
    (constraint_applied shift_candidate_alpha)
    (destination_availability_node_linked destination_availability_alpha destination_node_alpha)
    (dispatch_allocated shift_candidate_alpha)
    (dispatch_ready shift_candidate_alpha)
    (equipment_available equipment_resource_alpha)
    (equipment_available equipment_resource_beta)
    (loading_container_available loading_container_alpha)
    (loading_container_available loading_container_beta)
    (operator_alignment_confirmed shift_candidate_alpha)
    (operator_available driver_operator_alpha)
    (origin_availability_node_linked origin_availability_alpha origin_node_alpha)
    (route_task_profile_available route_task_profile_alpha)
    (service_window_available service_window_alpha)
    (service_window_available service_window_beta)
    (skill_certificate_available skill_certificate_alpha)
    (transport_leg_available transport_leg_alpha)
    (vehicle_allocated destination_availability_alpha)
    (vehicle_allocated origin_availability_alpha)
    (vehicle_allocated shift_candidate_alpha)
  )
  (:goal
    (and
      (candidate_dispatch_slot_linked origin_availability_alpha dispatch_slot_alpha)
      (candidate_prepared destination_availability_alpha)
      (candidate_prepared origin_availability_alpha)
      (candidate_task_profile_linked destination_availability_alpha route_task_profile_alpha)
      (compliance_certificate_available compliance_certificate_alpha)
      (destination_availability_confirmed destination_availability_alpha)
      (destination_availability_locked destination_availability_alpha)
      (destination_node_occupied destination_node_alpha)
      (destination_node_ready destination_node_alpha)
      (dispatch_allocated origin_availability_alpha)
      (dispatch_ready destination_availability_alpha)
      (dispatch_ready origin_availability_alpha)
      (dispatch_slot_available dispatch_slot_alpha)
      (dispatched origin_availability_alpha)
      (dispatched shift_candidate_alpha)
      (origin_availability_confirmed origin_availability_alpha)
      (origin_availability_locked origin_availability_alpha)
      (origin_node_occupied origin_node_alpha)
      (origin_node_ready origin_node_alpha)
      (transport_leg_assembled transport_leg_alpha)
      (transport_leg_destination_linked transport_leg_alpha destination_node_alpha)
      (transport_leg_loading_authorized transport_leg_alpha)
      (transport_leg_origin_linked transport_leg_alpha origin_node_alpha)
      (vehicle_available vehicle_unit_alpha)
      (vehicle_available vehicle_unit_gamma)
    )
  )
)
