(define (problem logistics_route_dispatch_cold_full_53_p7)
  (:domain driver_shift_compliant_route_planning)
  (:objects origin_availability_cold - origin_candidate_availability destination_availability_cold - destination_candidate_availability shift_candidate_cold_primary - schedule_candidate shift_candidate_cold_relay - schedule_candidate vehicle_unit_cold_origin - vehicle_unit vehicle_unit_cold_destination - vehicle_unit vehicle_unit_cold_linehaul - vehicle_unit route_task_profile_cold - route_task_profile driver_operator_cold - operator_resource cargo_payload_cold - cargo_payload origin_node_cold - origin_node destination_node_cold - destination_node transport_leg_cold - transport_leg loading_container_cold_primary - loading_container loading_container_cold_relay - loading_container equipment_resource_cold_lift - equipment_resource equipment_resource_cold_dock - equipment_resource service_window_cold_early - service_window service_window_cold_late - service_window dispatch_slot_cold - dispatch_slot skill_certificate_cold - skill_certificate operational_constraint_cold_primary - operational_constraint operational_constraint_cold_relay - operational_constraint compliance_certificate_cold - compliance_certificate)
  (:init
(vehicle_available vehicle_unit_cold_origin)
    (vehicle_available vehicle_unit_cold_destination)
    (vehicle_available vehicle_unit_cold_linehaul)
    (route_task_profile_available route_task_profile_cold)
    (operator_available driver_operator_cold)
    (cargo_available cargo_payload_cold)
    (origin_availability_node_linked origin_availability_cold origin_node_cold)
    (destination_availability_node_linked destination_availability_cold destination_node_cold)
    (transport_leg_available transport_leg_cold)
    (loading_container_available loading_container_cold_primary)
    (loading_container_available loading_container_cold_relay)
    (candidate_origin_availability_linked shift_candidate_cold_primary origin_availability_cold)
    (candidate_origin_availability_linked shift_candidate_cold_relay origin_availability_cold)
    (candidate_destination_availability_linked shift_candidate_cold_primary destination_availability_cold)
    (candidate_destination_availability_linked shift_candidate_cold_relay destination_availability_cold)
    (candidate_transport_leg_linked shift_candidate_cold_primary transport_leg_cold)
    (candidate_transport_leg_linked shift_candidate_cold_relay transport_leg_cold)
    (candidate_loading_container_linked shift_candidate_cold_primary loading_container_cold_primary)
    (candidate_loading_container_linked shift_candidate_cold_relay loading_container_cold_relay)
    (equipment_available equipment_resource_cold_lift)
    (equipment_available equipment_resource_cold_dock)
    (service_window_available service_window_cold_early)
    (service_window_available service_window_cold_late)
    (dispatch_slot_available dispatch_slot_cold)
    (skill_certificate_available skill_certificate_cold)
    (operational_constraint_available operational_constraint_cold_primary)
    (candidate_operational_constraint_linked shift_candidate_cold_primary operational_constraint_cold_primary)
    (candidate_operational_constraint_linked shift_candidate_cold_relay operational_constraint_cold_relay)
    (compliance_certificate_available compliance_certificate_cold)
  )
  (:goal
    (and
      (dispatched origin_availability_cold)
      (dispatched destination_availability_cold)
      (dispatched shift_candidate_cold_primary)
      (dispatched shift_candidate_cold_relay)
    )
  )
)
