(define (problem BLOCKS-6-0)
(:domain BLOCKS)
(:objects E A B C F D - block)
(:init (CLEAR D) (CLEAR F) (ONTABLE C) (ONTABLE B) (ON D A) (ON A C) (ON F E)
 (ON E B) (HANDEMPTY))
(:goal (and (ON C B) (ON B A) (ON A E) (ON E F) (ON F D)))
)