(define (problem logistics_route_dispatch_north_slice_22_p3)
  (:domain driver_shift_compliant_route_planning)
  (:objects origin_availability_north - origin_candidate_availability destination_availability_north - destination_candidate_availability shift_candidate_north_primary - schedule_candidate shift_candidate_north_relay - schedule_candidate vehicle_unit_north_origin - vehicle_unit vehicle_unit_north_destination - vehicle_unit vehicle_unit_north_linehaul - vehicle_unit route_task_profile_north - route_task_profile driver_operator_north - operator_resource cargo_payload_north - cargo_payload origin_node_north - origin_node destination_node_north - destination_node transport_leg_north - transport_leg loading_container_north_primary - loading_container loading_container_north_relay - loading_container equipment_resource_north_lift - equipment_resource equipment_resource_north_dock - equipment_resource service_window_north_early - service_window service_window_north_late - service_window dispatch_slot_north - dispatch_slot skill_certificate_north - skill_certificate operational_constraint_north_primary - operational_constraint operational_constraint_north_relay - operational_constraint compliance_certificate_north - compliance_certificate)
  (:init
    (candidate_compliance_certificate_linked shift_candidate_north_primary compliance_certificate_north)
    (candidate_created destination_availability_north)
    (candidate_created origin_availability_north)
    (candidate_created shift_candidate_north_primary)
    (candidate_created shift_candidate_north_relay)
    (candidate_destination_availability_linked shift_candidate_north_primary destination_availability_north)
    (candidate_destination_availability_linked shift_candidate_north_relay destination_availability_north)
    (candidate_dispatch_slot_linked shift_candidate_north_primary dispatch_slot_north)
    (candidate_finalized shift_candidate_north_primary)
    (candidate_loading_container_linked shift_candidate_north_primary loading_container_north_primary)
    (candidate_loading_container_linked shift_candidate_north_relay loading_container_north_relay)
    (candidate_operational_constraint_linked shift_candidate_north_primary operational_constraint_north_primary)
    (candidate_operational_constraint_linked shift_candidate_north_relay operational_constraint_north_relay)
    (candidate_origin_availability_linked shift_candidate_north_primary origin_availability_north)
    (candidate_origin_availability_linked shift_candidate_north_relay origin_availability_north)
    (candidate_prepared shift_candidate_north_primary)
    (candidate_transport_leg_linked shift_candidate_north_primary transport_leg_north)
    (candidate_transport_leg_linked shift_candidate_north_relay transport_leg_north)
    (candidate_vehicle_linked origin_availability_north vehicle_unit_north_origin)
    (candidate_vehicle_linked shift_candidate_north_primary vehicle_unit_north_linehaul)
    (cargo_available cargo_payload_north)
    (compliance_validation_complete shift_candidate_north_primary)
    (constraint_applied shift_candidate_north_primary)
    (destination_availability_node_linked destination_availability_north destination_node_north)
    (dispatch_allocated shift_candidate_north_primary)
    (dispatch_ready shift_candidate_north_primary)
    (equipment_available equipment_resource_north_dock)
    (equipment_available equipment_resource_north_lift)
    (loading_container_available loading_container_north_primary)
    (loading_container_available loading_container_north_relay)
    (operator_alignment_confirmed shift_candidate_north_primary)
    (operator_available driver_operator_north)
    (origin_availability_node_linked origin_availability_north origin_node_north)
    (route_task_profile_available route_task_profile_north)
    (service_window_available service_window_north_early)
    (service_window_available service_window_north_late)
    (skill_certificate_available skill_certificate_north)
    (transport_leg_available transport_leg_north)
    (vehicle_allocated origin_availability_north)
    (vehicle_allocated shift_candidate_north_primary)
    (vehicle_available vehicle_unit_north_destination)
  )
  (:goal
    (and
      (candidate_dispatch_slot_linked destination_availability_north dispatch_slot_north)
      (candidate_dispatch_slot_linked origin_availability_north dispatch_slot_north)
      (candidate_prepared destination_availability_north)
      (candidate_prepared origin_availability_north)
      (candidate_task_profile_linked destination_availability_north route_task_profile_north)
      (candidate_vehicle_linked destination_availability_north vehicle_unit_north_destination)
      (candidate_vehicle_linked shift_candidate_north_relay vehicle_unit_north_linehaul)
      (compliance_certificate_available compliance_certificate_north)
      (destination_availability_confirmed destination_availability_north)
      (destination_availability_locked destination_availability_north)
      (destination_node_occupied destination_node_north)
      (destination_node_ready destination_node_north)
      (dispatch_allocated destination_availability_north)
      (dispatch_allocated origin_availability_north)
      (dispatch_ready destination_availability_north)
      (dispatch_ready origin_availability_north)
      (dispatched origin_availability_north)
      (dispatched shift_candidate_north_primary)
      (origin_availability_confirmed origin_availability_north)
      (origin_availability_locked origin_availability_north)
      (origin_node_occupied origin_node_north)
      (origin_node_ready origin_node_north)
      (transport_leg_assembled transport_leg_north)
      (transport_leg_destination_linked transport_leg_north destination_node_north)
      (transport_leg_loading_authorized transport_leg_north)
      (transport_leg_origin_linked transport_leg_north origin_node_north)
      (vehicle_allocated destination_availability_north)
      (vehicle_allocated shift_candidate_north_relay)
      (vehicle_available vehicle_unit_north_origin)
    )
  )
)
